version: '3'

services:
  express:
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo_db
    # volumes:
    #   - ./:/app
    links:
      - mongo_db
    ports:
      - "3000:3000"
    restart: always
    environment:
      MONGO_DB_URI: mongodb://mongo_db:27017/gamma_api
  mongo_db:
    image: mongo:latest
    restart: always
