version: '3'

services:
  mongo_db:
    image: mongo:latest
    # restart: always
    ports:
      - "27017:27017"
  mongo_express:
    image:  mongo-express:latest
    depends_on:
      - mongo_db
    links:
      - mongo_db
    ports:
      - "8081:8081"
    # restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_BASICAUTH_USERNAME: ""
