version: '3'

services:
  express:
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo_db
    # volumes:
    #   - ./:/app
    links:
      - mongo_db
    ports:
      - "3000:3000"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Cx3UZQ5gxnX8hTYYEtxJYC
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_DB_URI: mongodb://admin:Cx3UZQ5gxnX8hTYYEtxJYC@mongo_db:27017/gamma_api?authSource=admin
  mongo_express:
    image:  mongo-express:latest
    depends_on:
      - mongo_db
    links:
      - mongo_db
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Cx3UZQ5gxnX8hTYYEtxJYC
